development:
  adapter: postgresql
  encoding: unicode
  database: borrowers_dev
  host: localhost
  password: air
  username: postgres

staging:
  adapter: postgresql
  encoding: unicode
  database: borrowers_dev
  host: localhost
  password: air
  username: postgres